services:
  db:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-aula_views}
      - MYSQL_USER=${MYSQL_USER:-aluno}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_ADMIN_USER=${DB_ADMIN_USER:-}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD:-}
      - TZ=${TZ:-America/Sao_Paulo}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
